# Generated by Django 3.2.4 on 2021-06-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotParse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=10000, unique=True)),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
